name: PrettyLights
main: com.xorinc.prettylights.PrettyLightsPlugin
version: 0.0.1
author: dr_Xor
website: http://github.com/drXor
description: >
    Spigot plugin that generates cosmetic particles around players
#softdepend: [VanishNoPacket]
commands: 
  prettylights:
    description: Main plugin command
    aliases: [particles]
    permission: prettylights.use
    usage: /<command> [effect|reload|off]

permissions:
  prettylights.use:
      description: Allows use of the main plugin command
      default: op
