name: PrettyLights
main: com.xorinc.prettylights.PrettyLightsPlugin
version: 1.0.0
author: dr_Xor
website: http://github.com/drXor
description: >
    Spigot plugin that generates cosmetic particles around players
commands: 
  prettylights:
    description: Main plugin command
    aliases: [particles, particle]
    permission: prettylights.use
    usage: /<command> [effect|off|reload]

permissions:
  prettylights.use:
      description: Allows use of the main plugin command
      default: op
